color = input("Enter a color: ")
pluralNoun = input("Enter a prural noun: ")
celebrity = input("Enter a celebrity: ")
print("Roses are ", color)
print(pluralNoun + " are blue")
print("I Love", celebrity)